[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[fuzz]
runs = 50

[invariant]
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/config/README.md#all-options